import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Suzuki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white sticky top-0 z-50">
        {/* Header */}
        <Header />

        {/* Nav */}
        <Nav />
      </div>

      {/* Hero */}
      <Hero />

      {/* Content */}

      {/* Footer */}
    </div>
  );
}
