import { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Content from "../components/Content";
import Footer from "../components/Footer";
import Menu from "../components/Menu";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <div className="relative">
      <Head>
        <title>Suzuki Rosebank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white sticky top-0 z-50 ">
        {/* Header */}
        <Header />

        {/* Nav */}
        <Nav
          menuOpen={menuOpen}
          toggleMenu={() => setMenuOpen((prev) => !prev)}
        />
      </div>

      <main>
        {/* Hero */}
        <Hero />

        {/* Content */}
        <Content />

        {/* Footer */}
        <Footer />
      </main>

      {/* Menu */}
      <Menu menuOpen={menuOpen} />
    </div>
  );
}
